//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/BBSCodeParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Casasoft.BBS.Parser {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IBBSCodeParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public partial class BBSCodeParserBaseListener : IBBSCodeParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeElement([NotNull] BBSCodeParser.BbsCodeElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeElement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeElement([NotNull] BBSCodeParser.BbsCodeElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeContent([NotNull] BBSCodeParser.BbsCodeContentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeContent"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeContent([NotNull] BBSCodeParser.BbsCodeContentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeAttribute([NotNull] BBSCodeParser.BbsCodeAttributeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeAttribute"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeAttribute([NotNull] BBSCodeParser.BbsCodeAttributeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeAttributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeAttributeName([NotNull] BBSCodeParser.BbsCodeAttributeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeAttributeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeAttributeName([NotNull] BBSCodeParser.BbsCodeAttributeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeAttributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeAttributeValue([NotNull] BBSCodeParser.BbsCodeAttributeValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeAttributeValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeAttributeValue([NotNull] BBSCodeParser.BbsCodeAttributeValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeTagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeTagName([NotNull] BBSCodeParser.BbsCodeTagNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeTagName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeTagName([NotNull] BBSCodeParser.BbsCodeTagNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="BBSCodeParser.bbsCodeChardata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBbsCodeChardata([NotNull] BBSCodeParser.BbsCodeChardataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="BBSCodeParser.bbsCodeChardata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBbsCodeChardata([NotNull] BBSCodeParser.BbsCodeChardataContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Casasoft.BBS.Parser
